package organization

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

type OrganizationsInterface interface {
	// Get organizations. Authorization limits are applied to requesting user.

	// It is handler for GET /organizations
	Get(http.ResponseWriter, *http.Request)

	// Create new organization
	// It is handler for POST /organizations
	Post(http.ResponseWriter, *http.Request)

	// Get organization info
	// It is handler for GET /organizations/{globalid}
	globalidGet(http.ResponseWriter, *http.Request)

	// Update organization info
	// It is handler for PUT /organizations/{globalid}
	globalidPut(http.ResponseWriter, *http.Request)

	// Assign a member to organization
	// It is handler for POST /organizations/{globalid}/members
	globalidmembersPost(http.ResponseWriter, *http.Request)

	// Remove a member from organization
	// It is handler for DELETE /organizations/{globalid}/members/{username}
	globalidmembersusernameDelete(http.ResponseWriter, *http.Request)
}

func OrganizationsInterfaceRoutes(r *mux.Router, i OrganizationsInterface) {
	r.HandleFunc("/organizations", i.Get).Methods("GET")
	r.HandleFunc("/organizations", i.Post).Methods("POST")
	r.HandleFunc("/organizations/{globalid}", i.globalidGet).Methods("GET")
	r.HandleFunc("/organizations/{globalid}", i.globalidPut).Methods("PUT")
	r.HandleFunc("/organizations/{globalid}/members", i.globalidmembersPost).Methods("POST")
	r.HandleFunc("/organizations/{globalid}/members/{username}", i.globalidmembersusernameDelete).Methods("DELETE")
}
