package userorganization

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
)

type UserorganizationsInterface interface {
	// Get the list organizations a user is owner or member of
	// It is handler for GET /users/{username}/organizations
	Get(http.ResponseWriter, *http.Request)

	// Accept membership in organization
	// It is handler for POST /users/{username}/organizations/{globalid}/roles/{role}
	globalidrolesrolePost(http.ResponseWriter, *http.Request)

	// Reject membership invitation in an organization.

	// It is handler for DELETE /users/{username}/organizations/{globalid}/roles/{role}
	globalidrolesroleDelete(http.ResponseWriter, *http.Request)
}

func UserorganizationsInterfaceRoutes(r *mux.Router, i UserorganizationsInterface) {
	r.HandleFunc("/users/{username}/organizations", i.Get).Methods("GET")
	r.HandleFunc("/users/{username}/organizations/{globalid}/roles/{role}", i.globalidrolesrolePost).Methods("POST")
	r.HandleFunc("/users/{username}/organizations/{globalid}/roles/{role}", i.globalidrolesroleDelete).Methods("DELETE")
}
