#%RAML 1.0
title: ItsYouOnline
version: 0.1
baseUri: /
types:
  Company:
    properties:
        globalid:
            type: string
        publicKeys:
            type: string[]
            maxItems: 20
        expire:
            type: date
            required: false
        organizations:
            type: string[]
            maxItems: 100
            required: false
        info:
            type: string[]
            maxItems: 20
            required: false
        taxnr:
            type: string
            required: false
    example:
        globalid: ILikeCandy
        publicKeys:
            - 18SGHYSi8JCvAvTU6Ymv1HRmmu86Mq2Ypz
        expire: 2018-10-20
        info:
          - info@ilikecandy.com
        taxnr: BE1234123412341234

  companyview:
        type: Company

/companies:
  post:
    description: Register a new company
    body:
        application/json:
            type: company
  /{globalId}:
    put:
      description: Update existing company. Updating ``globalId`` is not allowed.
      responses:
        200:
          body:
            application/json:
              type: company
        403:
          description: Updating globalId is Forbidden!
    /info:
      get:
        responses:
            200:
                body:
                    application/json:
                        type: companyview
    /validate:
      get:
        queryParameters:
            token:
                type: string

    /contracts:
      get:
        description: Get the contracts where the organization is 1 of the parties. Order descending by date.
        queryParameters:
          includeExpired:
              type: boolean
              description: Include the expired contracts, by default only the active contracts are returned.
              required: false
          start:
              type: integer
              description: Start offset, useful for paging. Default is `0`.
              required: false
          max:
              type: integer
              description: Max page size, useful for paging. Default is `50`.
              required: false
              maximum: 250
