#%RAML 1.0
title: ItsYouOnline
version: 0.1
baseUri: /
securitySchemes:
  - oauth_2_0:
        !include securitySchemes/oauth_2_0.raml
types:
  Company:
    properties:
        globalid:
            type: string
            minLength: 3
            maxLength: 150
        publicKeys:
            type: string[]
            maxItems: 20
        expire:
            type: date
            required: false
        organizations:
            type: string[]
            maxItems: 100
            required: false
        info:
            type: string[]
            maxItems: 20
            required: false
        taxnr:
            type: string
            required: false
    example:
        globalid: ILikeCandy
        publicKeys:
            - 18SGHYSi8JCvAvTU6Ymv1HRmmu86Mq2Ypz
        expire: 2018-10-20
        info:
          - info@ilikecandy.com
        taxnr: BE1234123412341234

  companyview:
        type: Company

securedBy: [ oauth_2_0 ]
/companies:
  post:
    description: Register a new company
    body:
        application/json:
            type: Company
  get:
    displayName: GetCompanyList
    description: |
          Get companies. Authorization limits are applied to requesting user.
    responses:
          200:
            body:
              application/json:
                type: Company[]
  /{globalId}:
    get:
      securedBy: [oauth_2_0: { scopes: [ "company:read", "company:admin" ] } ]
      description: Get organization info
      responses:
        200:
          body:
            application/json:
              type: Company
        401:
          description: Unauthorized
        404:
          description: Not found
    put:
      securedBy: [oauth_2_0: { scopes: [ "company:admin" ] } ]
      description: Update existing company. Updating ``globalId`` is not allowed.
      responses:
        200:
          body:
            application/json:
              type: Company
        403:
          description: Updating globalId is Forbidden!
    /info:
      securedBy: [oauth_2_0: { scopes: [ "company:info" ] } ]
      get:
        responses:
            200:
                body:
                    application/json:
                        type: companyview
    /validate:
      get:
        queryParameters:
            token:
                type: string

    /contracts:
      get:
        securedBy: [oauth_2_0: { scopes: [ "company:admin", "company:contracts:read" ] } ]
        description: Get the contracts where the organization is 1 of the parties. Order descending by date.
        queryParameters:
          includeExpired:
              type: boolean
              description: Include the expired contracts, by default only the active contracts are returned.
              required: false
          start:
              type: integer
              description: Start offset, useful for paging. Default is `0`.
              required: false
          max:
              type: integer
              description: Max page size, useful for paging. Default is `50`.
              required: false
              maximum: 250
