#%RAML 1.0
title: Contracts
version: 0.1
baseUri: /
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml

types:
  Signature:
    properties:
      signedBy: string
      date: datetime
      publicKey:
        type: string
        description: The public key used
      signature:
        type: string

  Contract:
    properties:
      parties:
        type: string[]
        minItems: 2
        maxItems: 20
        uniqueItems: true
      content: string
      contractType:
        type: string
        maxLength: 40
        description: Free field to be used for tags by the party creating a contract
      invalidates?:
        type: string[]
        maxItems: 10
        description: list of contractId's this contract invalidates.
      extends?:
        type: string[]
        maxItems: 10
        description: list of contractId's this contract is an extension upon
      expires: datetime
      contractId:
        type: string
        description: |
          The contractId is the hash of the parties, the content, the contractType,  and the expiration date.
          To calculate the hash, take the json representation of the contract without the id and signatures, trim the newlines or spaces (except when they appear in the values) and encode in  utf8.
          From this result, take a SHA256 followed by a RIPEMD160, next base58CheckEncode the result with a 0x00 prefix.

      signatures: Signature[]

securedBy: [ oauth_2_0 ]
/contracts:
  post:
    description: Create a new contract.
    responses:
      201:
        body:
          application/json:
            type: Contract
      401:
        description: Unauthorized

  /{contractId}:
    get:
      securedBy: [oauth_2_0: { scopes: [ "contract:read" ] } ]
      description: Get a contract
      responses:
        200:
          body:
            application/json:
              type: Contract
        404:
          description: Not found
    /signatures:
        post:
          securedBy: [oauth_2_0: { scopes: [ "contract:participant" ] } ]
          description: Sign a contract
          body:
            application/json:
              type: Signature
