#%RAML 1.0
title: ItsYouOnline
version: 0.1
baseUri: /
securitySchemes:
  - oauth_2_0:
        !include securitySchemes/oauth_2_0.raml

types:
  Organization:
    properties:
      globalid:
        type: string
        minLength: 3
        maxLength: 150
      publicKeys:
        type: string[]
        maxItems: 20
      dns:
        type: string[]
        maxItems: 100
        description: List of organization DNS.
      owners:
        type: string[]
        maxItems: 20
        description: List of users `usernames`.
      members:
        type: string[]
        maxItems: 2000
        description: List of users who are member in this organization.
      includes:
        type: string[]
        maxItems: 100
        description: globalId of sub organizations

    example:
      globalid: greenitglobe
      publicKeys:
        - 1A9WWh6iAE4RZGN7axy6xZbuWuLknqWLrV
      dns:
        - greenitglobe.com
      owners:
        - user1
        - user2
        - user3
      members:
        - user4
      includes:
        - admin.greenitglobe.com

  member:
    properties:
      username:
        type: string
        description: Used when assigning a member to an organization.

    example:
      username: bob

  Invitation:
    properties:
        user: string
        role:
          type: string
          enum: [owner, member]
        created: date

    example:
      user: bob
      role: owner
      created: Sun, 06 Nov 1994 08:49:37 GMT

securedBy: [ oauth_2_0 ]
/organizations:
  post:
    displayName: CreateNewOrganization
    description: Create a new organization. 1 user should be in the owners list. Validation is performed to check if the securityScheme allows management on this user.
    body:
      application/json:
        type: Organization
    responses:
      201:
        body:
          application/json:
            type: Organization
      401:
        description: Unauthorized
  get:
    description: |
      Get organizations. Authorization limits are applied to requesting user.
    responses:
      200:
        body:
          application/json:
            type: Organization[]

  /{globalid}:
    get:
      securedBy: [oauth_2_0: { scopes: [ "organization:member", "organization:owner" ] } ]
      description: Get organization info
      responses:
        200:
          body:
            application/json:
              type: Organization
        401:
          description: Unauthorized
        404:
          description: Not found
    put:
      securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
      description: Update organization info
      body:
        application/json:
          type: Organization
      responses:
        200:
          body:
            application/json:
              type: Organization
        401:
          description: Unauthorized
        404:
          description: Not found

    /members:
      post:
        securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
        description: Assign a member to organization.
        body:
          application/json:
            type: member
        responses:
          201:
            description: Member assigned successfully
            body:
              application/json:
                type: member
          401:
            description: Unauthorized
          404:
            description: Not found

      /{username}:
        delete:
          securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
          description: Remove a member from organization
          responses:
            204:
              description: Member deleted successfully
            401:
              description: Unauthorized
            404:
              description: The user or the organization does not exist.
            409:
              description: The user already is a member.

    /owners:
      post:
        securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
        description: Invite a user to become owner of an organization.
        body:
            application/json:
              type: member
        responses:
            201:
              description: Invite created successfully
              body:
                application/json:
                  type: member
            401:
              description: Unauthorized
            404:
              description: The user or the organization does not exist.
            409:
              description: The user already is an owner.

      /{username}:
          delete:
            securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
            description: Remove an owner from organization
            responses:
              204:
                description: Owner removed successfully
              401:
                description: Unauthorized
              404:
                description: Not found

    /contracts:
      securedBy: [oauth_2_0: { scopes: [ "organization:owner", "organization:contracts:read" ] } ]
      get:
        displayName: GetContracts
        description: Get the contracts where the organization is 1 of the parties. Order descending by date.
        queryParameters:
          includeExpired:
              type: boolean
              description: Include the expired contracts, by default only the active contracts are returned.
              required: false
          start:
              type: integer
              description: Start offset, useful for paging. Default is `0`.
              required: false
          max:
              type: integer
              description: Max page size, useful for paging. Default is `50`.
              required: false
              maximum: 250

    /invitations:
      securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
      get:
        displayName: GetPendingInvitations
        description: Get the list of pending invitations for users to join this organization.
        responses:
            200:
              body:
                application/json:
                  type: Invitation[]

      /{username}:
        delete:
            displayName: RemovePendingInvitation
            description: Cancel a pending invitation.
            responses:
                204:
                  description: Invitation cancelled

    /apisecrets:
      description: API secrets are the oauth2 client secrets needed to access the api.
      securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
      get:
        displayName: GetAPISecretLabels
        description: Get the list of labels that are defined for active api secrets. The secrets themselves are not included.
        responses:
            200:
              body:
                application/json:
                    type: string[]
      post:
        displayName: CreateNewAPISecret
        description: Create a new API Secret
        body:
          application/json:
            properties:
              label:
                type: string
                maxLength: 50
                minLength: 2
        responses:
            201:
              body:
                application/json:
                    properties:
                       label: string
                       secret: string
            409:
                description: Label is already used.
      /{label}:
        get:
          displayName: GetAPISecret
          responses:
            200:
                body:
                    application/json:
                     properties:
                        label: string
                        secret: string
            404:
                description: Not found
        put:
          displayName: UpdateAPISecretLabel
          description: Updates the label of the secret
          body:
            application/json:
              properties:
                label:
                  type: string
                  maxLength: 50
                  minLength: 2
          responses:
            201:
                description: Renamed
            409:
                description: New label is already used
        delete:
          displayName: DeleteAPISecret
          description: Removes an API secret
          responses:
              204:
                description: API secret removed
