#%RAML 1.0
title: ItsYouOnline
version: 0.1
baseUri: /users
types:
  phonenumber:
    pattern: ^\+[0-9]+$
  address:
    properties:
        city:
            type: string
            maxLength: 30
        street:
            type: string
            maxLength: 50
        nr:
            type: string
            maxLength: 10
        other:
            type: string
            maxLength: 30
            required: false
        country:
            type: string
            maxLength: 40
        postalcode:
            type: string
            maxLength: 20
  user:
    properties:
        username:
            type: string
            maxLength: 30
        expire:
            type: date
            required: false
        email:
          required: false
          properties:
            []:
              type: string
        phone:
          required: false
          properties:
            []:
              type: phonenumber
        address:
          required: false
          properties:
            []:
              type: address

    example:
        username: bob
        expire: 2018-10-20
        email:
            work: bob@company.com
            home: bob@example.com
            "dance club": bob@linedanceclub.example.org
        phone:
          be: +3212341234123
          eg: +2012341234123
        address:
            home:
                city: Springfield
                street: Main street
                nr: 45B
                country: Tomorrowland
                postalcode: T-9450

  userview:
    properties:
        username:
            type: string
        email:
            type: string[]
            required: false
        phone:
            type: phonenumber[]
            required: false
        address:
            type: address[]
            required: false

/users:
  post:
    displayName: Create a new user
    body:
        application/json:
            type: user
  /{username}/info:
    get:
        responses:
            200:
                body:
                    application/json:
                        type: userview
  /{username}/validate:
    get:
        queryParameters:
            token:
                type: string
