#%RAML 1.0
title: ItsYouOnline
version: 0.1
baseUri: /
securitySchemes:
  - oauth_2_0: !include securitySchemes/oauth_2_0.raml
types:

      JoinOrganizationInvitation:
        properties:
            organization: string
            user: string
            role:
                type: string
                enum: [owner, member]

securedBy: [ oauth_2_0 ]
/users/{username}/organizations:
  securedBy: [oauth_2_0: { scopes: [ "user:admin" ] } ]
  get:
    description: Get the list organizations a user is owner or member of
    responses:
      200:
        body:
          application/json:
            properties:
              owner: string[]
              member: string[]

  /{globalid}/roles/{role}:
    post:
      description: Accept membership in organization
      body:
        application/json:
          type: JoinOrganizationInvitation
      responses:
        201:
          body:
            application/json:
              type: JoinOrganizationInvitation
    delete:
      description: |
        Reject membership invitation in an organization.
      responses:
        204:
          description: |
            Succesfully rejected invitation.
