package notification

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

type UsersusernamenotificationsInterface interface {
	// Get the list of notifications, these are pending invitations or approvals
	// It is handler for GET /users/{username}/notifications
	Get(http.ResponseWriter, *http.Request)
}

func UsersusernamenotificationsInterfaceRoutes(r *mux.Router, i UsersusernamenotificationsInterface) {
	r.HandleFunc("/users/{username}/notifications", i.Get).Methods("GET")
}
